### ISSUE TITLE
Support javax.inject.Inject annotation in Jersey resources

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-jersey#44]
Currently only `@com.google.inject.Inject` annotation is resolved in Jersey resources and this can lead to confusion.
`@javax.inject.Inject` annotation is always on classpath (as compile dependency of Guice) and working fine in other Bootique parts.
It could be implemented exactly as Guice annotation resolver we already have.

**Comment by dumy-org-00** [comment]
Turned out that Jersey internal DI manager uses `javax.inject.Inject` annotation, so this task is a little bit harder.

**Comment by stariy95** [comment]
Turned out that Jersey internal DI manager uses javax.inject.Inject annotation, so this task is a little bit harder.

**Comment by andrus** [comment]
Now that I applied 2.27 upgrade PR, wonder if there's a path for this task implementation as well?

**Comment by andrus** [comment]
I think this is fixed in 2.0 as a result of the switch to bootique-di.
