### ISSUE TITLE
bootique-jersey-jackson-1.1.jar does not contain *.class files

### ISSUE THREAD

**Issue by Fubuchi** [bootique/bootique-jersey#54]
From 
- maven central : https://mvnrepository.com/artifact/io.bootique.jersey/bootique-jersey-jackson/1.1
- jcenter: https://bintray.com/bootique/releases/bootique-jersey/view/files/io/bootique/jersey/bootique-jersey-jackson/1.1#files/io/bootique/jersey/bootique-jersey-jackson/1.1

The bootique-jersey-jackson-1.1.jar only contain META-INF folder and there is no *.class file, so I can not use `JerseyJacksonModule`

Here is my gradle config:
```
dependencies {
    implementation platform("io.bootique.bom:bootique-bom:1.1")
    implementation "io.bootique.jersey:bootique-jersey"
    implementation "io.bootique.jersey:bootique-jersey-jackson"
    implementation "io.bootique.logback:bootique-logback"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.6.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.6.2"
}
```

**Comment by andrus** [comment]
Hi. `JerseyJacksonModule` was only added in Bootique 2.0. In Bootique 1.1  `io.bootique.jersey:bootique-jersey-jackson` is a simple library (not a Bootique module) with the only purpose being to place the right Jersey and Jackson dependencies on the app classpath. So in 1.1 you can add it as a dependency, but can't invoke JerseyJacksonModule.
