### ISSUE TITLE
Support JAX-RS @ApplicationPath

### ISSUE THREAD

**Issue by bannmann** [bootique/bootique-jersey#56]
I want to set a base application path for all JAX-RS resource classes using an application class:

```
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/api")
public class MyApplication extends Application
{
}
```
Neither the docs nor the example makes it clear how to set this up with bootique-jersey. I tried putting `MyApplication` into the package (of the class) passed to `JerseyModule.extend(binder).addPackage(OneOfMyResources.class)`, but the application class is not used.

I guess this use case is simply not supported yet by the bootique-jersey glue code (or at least not in 1.2). Please fix this.

How about adding the following method to `JerseyModuleExtender`?

    <T extends Application> withApplicationClass(Class<T> applicationClass)

I think bootique could then simply create the Jersey `ResourceConfig` using that application class, similarly to how [JerseyServletContainerInitializer does it](https://github.com/jersey/jersey/blob/faa809da43538ce31076b50f969b4bd64caa5ac9/containers/jersey-servlet/src/main/java/org/glassfish/jersey/servlet/init/JerseyServletContainerInitializer.java#L278). (Note: I didn't bother checking the exact jersey version as I guess that API is fairly stable).

Alternatively, `JerseyModuleExtender` could have a method to set the application path, but I would prefer sticking to the JAX-RS API as much as possible - in this case, adding `@ApplicationPath` to the application class, but letting the developer specify the application class instead of having it discovered automatically (which I presume is not possible/easy/performant with Guice).

**Comment by andrus** [comment]
> I want to set a base application path for all JAX-RS resource classes using an application class

You can do it with configuration instead. Common path for all Jersey resources can be specified via Jersey servlet "urlPattern":

```yaml
jersey:
   urlPattern: "/api/*"
```

> How about adding the following method to JerseyModuleExtender?

I was always wondering whether we need explicit support for JAX-RS "application", considering that the app assembly is done via Bootique. While I use e.g. Features extensively, I haven't found a need for the application yet. Open for discussion.

**Comment by bannmann** [comment]
> I was always wondering whether we need explicit support for JAX-RS "application" (...) Open for discussion.

Well, to conform to the JAX-RS spec, Bootique would have to support application classes. But I guess that this is not the goal, and that's okay.

On a more practical note, supporting application classes would allow interoperability between different JAX-RS implementations. For example, I just had to switch from `bootique-jersey` to `bootique-cxf-jaxrs`, so the `urlPattern` configuration shown above would no longer apply. With `@ApplicationPath`, this would not be the case.

**Comment by andrus** [comment]
I suppose supporting `@ApplicationPath` will be following a bunch of precedents. We support both servlet and JAX-RS  spec annotations after all. So +1 on this.

**Comment by andrus** [comment]
Done:

```java
JerseyModule.extend(b).setApplication(MyApp.class)
```

This supports both `@ApplicationPath` annotation processing, as well as loading the resources defined by the custom app class. So I am going to rename the task to reflect full support for custom Application.
